// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppConfig: typeof import('./src/components/cp/AppConfig.vue')['default']
    AppFooter: typeof import('./src/components/cp/AppFooter.vue')['default']
    AppLogomenu: typeof import('./src/components/cp/AppLogomenu.vue')['default']
    AppMenu: typeof import('./src/components/cp/AppMenu.vue')['default']
    AppMenuItem: typeof import('./src/components/cp/AppMenuItem.vue')['default']
    AppSidebar: typeof import('./src/components/cp/AppSidebar.vue')['default']
    AppSubmenu: typeof import('./src/components/cp/AppSubmenu.vue')['default']
    AppTopBar: typeof import('./src/components/cp/AppTopBar.vue')['default']
    AppTopBarUser: typeof import('./src/components/cp/AppTopBarUser.vue')['default']
    BlockViewer: typeof import('./src/components/BlockViewer.vue')['default']
    CodeHighlight: typeof import('./src/components/CodeHighlight.vue')['default']
    Games: typeof import('./src/components/Games.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Slider: typeof import('./src/components/Slider.vue')['default']
    Winners: typeof import('./src/components/Winners.vue')['default']
  }
}
