// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddAmbassador: typeof import('./src/components/AddAmbassador.vue')['default']
    AddAuthor: typeof import('./src/components/AddAuthor.vue')['default']
    AddMaster: typeof import('./src/components/AddMaster.vue')['default']
    AddSupport: typeof import('./src/components/AddSupport.vue')['default']
    AppConfig: typeof import('./src/components/cp/AppConfig.vue')['default']
    AppFooter: typeof import('./src/components/cp/AppFooter.vue')['default']
    AppMenu: typeof import('./src/components/cp/AppMenu.vue')['default']
    AppSubmenu: typeof import('./src/components/cp/AppSubmenu.vue')['default']
    AppTopBar: typeof import('./src/components/cp/AppTopBar.vue')['default']
    Counter: typeof import('./src/components/Counter.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
